# Generated by Django 3.0.1 on 2019-12-31 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('idg', models.AutoField(primary_key=True, serialize=False)),
                ('gestor_nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('cod_med', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento_dci', models.CharField(max_length=200)),
                ('medicamento_nome', models.CharField(max_length=200)),
                ('medicamento_dosagem', models.CharField(max_length=200)),
                ('medicamento_estadoauth', models.CharField(max_length=100)),
                ('medicamento_generico', models.CharField(max_length=100)),
                ('medicamento_titular', models.CharField(max_length=200)),
                ('medicamento_formafarmaceutica', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idm', models.AutoField(primary_key=True, serialize=False)),
                ('med_nome', models.CharField(max_length=200, unique=True)),
                ('med_nif', models.IntegerField()),
                ('med_ced', models.IntegerField(unique=True)),
                ('med_cc', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('sec_nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('idu', models.AutoField(primary_key=True, serialize=False)),
                ('utente_nome', models.CharField(max_length=200, unique=True)),
                ('utente_cc', models.IntegerField(unique=True)),
                ('utente_nif', models.IntegerField()),
                ('utente_morada', models.CharField(max_length=200)),
                ('utente_cp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('prescricao_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('prescricao_data', models.DateField()),
                ('prescricao_hora', models.TimeField()),
                ('prescricao_aviada', models.BooleanField(default=False)),
                ('quantidade', models.IntegerField()),
                ('idm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Medico')),
                ('idu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Utente')),
                ('medprescrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('ide', models.AutoField(primary_key=True, serialize=False)),
                ('exame_data', models.DateField()),
                ('exame_hora', models.TimeField()),
                ('exame_tipo', models.CharField(max_length=200)),
                ('exame_local', models.CharField(max_length=2000)),
                ('exame_duracao', models.FloatField()),
                ('exame_preco', models.FloatField()),
                ('idm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Medico')),
                ('idu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Utente')),
            ],
        ),
    ]
